gamepad: fix ABI break in wpe_gamepad_client_interface
In #134, the analog_button_changed field was added to
wpe_gamepad_client_interface, but it missed removing one of trailing
reserved fields, so the struct size grew and broke upstream WPE build
in developer mode:

```
GamepadLibWPE.cpp:62:5: error: missing field '_wpe_reserved3' initializer [-Werror,-Wmissing-field-initializers]
```

(cherry picked from commit 3acbb9fa0b51ee71fb4c1e4ce0b9c00c4112c8f8)